import type { Metadata } from "next";
import { Inter, Lato, Nunito, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import UserNavbar from "./components/UserNavbar";

export const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});
export const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});
export const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`!${lato.className} flex h-full w-full relative overflow-auto`}
      >
        <div className="sticky top-0 left-0 bottom-0 h-full">
          <Sidebar />
        </div>
        <div className="flex flex-col gap-5 h-full w-full px-24 my-5 overflow-auto">
          {/* navbar */}
          <Navbar />
          {/* user navbar */}
          <UserNavbar />

          {children}
        </div>
      </body>
    </html>
  );
}
